# Generated by Django 4.2.7 on 2025-01-16 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id_ent', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id_fes', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeUser',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_use', models.AutoField(primary_key=True, serialize=False)),
                ('ci', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('type_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.typeuser')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id_sale', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('entrace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.entrance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.user')),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id_prese', models.AutoField(primary_key=True, serialize=False)),
                ('scenery', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.festival')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.user')),
            ],
        ),
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id_lit', models.AutoField(primary_key=True, serialize=False)),
                ('literature', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.user')),
            ],
        ),
        migrations.AddField(
            model_name='festival',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.user'),
        ),
        migrations.AddField(
            model_name='entrance',
            name='festival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.festival'),
        ),
    ]
