# Generated by Django 4.2.7 on 2025-01-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_licence_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='date',
            field=models.DateField(),
        ),
    ]
